name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout GitHub repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # 2️⃣ Set Git identity (required)
      - name: Configure Git
        run: |
          git config --global user.name "rajats2468"
          git config --global user.email "rudradna2468@gmail.com"

      # 3️⃣ Push to Hugging Face (force sync)
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://rajats07:$HF_TOKEN@huggingface.co/spaces/rajats07/Search_Engine_llm
          git push hf main --force
